#pragma once

#define		TO_FIND_MAINWINDOW_DEFINED_CLASSNAME	L"SERVER_WINDOW_CLASSNAME_2016_3_28"
#define		TO_FIND_MAINWINDOW_DEFINED_NAME			L"SERVER_WINDOW_2016_3_28"


#define		WM_REMOTECLIENT_MESSAGE					WM_APP + 100
#define		WM_SHOW_SERVERWINDOW					WM_APP + 101
#define		WM_CLOSE_SERVERWINDOW					WM_APP + 102